[package]
name = "goals"
version = "0.1.0"
edition = "2021"

[dependencies]
state = { path = "../state" }
events = { path = "../events" }
thiserror = { workspace = true }
influence = { path = "../influence" }
serde = { workspace = true, features = ["derive"] }
log = { workspace = true }
