[package]
name = "ffi"
version = "0.1.0"
edition = "2021"

[dependencies]
engine = { path = "../engine" }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
tokio = { workspace = true, features = ["rt-multi-thread"] }
