[package]
name = "path"
version = "0.1.0"
edition = "2024"

[dependencies]
influence = { path = "../influence" }

[dev-dependencies]
criterion = { workspace = true }

[[bench]]
name = "cache_bench"
harness = false
