[package]
name = "rl"
version = "0.1.0"
edition = "2024"

[dependencies]
tch = { workspace = true }
rand = { workspace = true }
thiserror = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
