[package]
name = "rl"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = { workspace = true }
ndarray = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true, features = ["derive"] }
bincode = { workspace = true }
