[package]
name = "events"
version = "0.1.0"
edition = "2021"

[dependencies]
crossbeam = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
state = { path = "../state" }
thiserror = { workspace = true }




common = { path = "../common" }

