[package]
name = "influence"
version = "0.1.0"
edition = "2024"

[dependencies]
state = { path = "../state" }
thiserror = { workspace = true }

[dev-dependencies]
proptest = { workspace = true }
criterion = { workspace = true }

[[bench]]
name = "update"
harness = false
