[package]
name = "example_crate"
version = "0.2.0"
edition = "2021"

[dependencies]
thiserror = "1"
shaku = { version = "0.6", features = ["derive"] }

[dev-dependencies]
proptest = "1"

[features]
default = []
