[package]
name = "bombs"
version = "0.1.0"
edition = "2024"

[dependencies]
petgraph = { workspace = true }
serde = { workspace = true }
thiserror = { workspace = true }
state = { path = "../state" }

[dev-dependencies]
proptest = { workspace = true }
