[package]
name = "bot"
version = "0.1.0"
edition = "2024"

[dependencies]
events = { path = "../events" }
state = { path = "../state" }
crossbeam = { workspace = true }
thiserror = { workspace = true }
