name: CI

on:
  push:
    paths:
      - 'Docs/examples/example_crate/**'
      - '.github/workflows/ci.yml'
  pull_request:
    paths:
      - 'Docs/examples/example_crate/**'
      - '.github/workflows/ci.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain: [stable, beta, nightly]
    steps:
      - uses: actions/checkout@v3
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          profile: minimal
      - run: cargo fmt --all -- --check
        working-directory: Docs/examples/example_crate
      - run: cargo clippy --all-targets -- -D warnings
        working-directory: Docs/examples/example_crate
      - run: cargo test --all
        working-directory: Docs/examples/example_crate
      - run: cargo test --doc
        working-directory: Docs/examples/example_crate
      - run: cargo doc --no-deps
        working-directory: Docs/examples/example_crate
